# Generated by Django 5.2.11 on 2026-03-06 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_subcategory_category_and_more'),
        ('seller', '0006_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.sellerprofile'),
        ),
    ]
