# Generated by Django 5.2.11 on 2026-04-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_reviews_rating'),
        ('seller', '0011_remove_productvarient_attribute_values_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.sellerprofile'),
            preserve_default=False,
        ),
    ]
