# Generated by Django 5.2.11 on 2026-03-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
