# Generated by Django 5.2.11 on 2026-03-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='seller_profile_pic/'),
        ),
    ]
