# Generated by Django 5.2.11 on 2026-03-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_sellerprofile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='profile_pic',
            new_name='shop_logo',
        ),
    ]
