# Generated by Django 5.2.11 on 2026-03-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_attribute_attributevalues_productvarient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvarient',
            name='attribute_values',
        ),
        migrations.AddField(
            model_name='productvarient',
            name='attribute_values',
            field=models.ManyToManyField(to='seller.attributevalues'),
        ),
    ]
