# Generated by Django 5.2.11 on 2026-03-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_remove_productvarient_attribute_values_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributevalues',
            old_name='values',
            new_name='value',
        ),
    ]
