# Generated by Django 5.2.11 on 2026-03-21 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_rename_values_attributevalues_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.category'),
        ),
    ]
