# Generated by Django 5.2.11 on 2026-03-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_remove_attribute_category_attribute_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='subcategory',
            name='attributes',
            field=models.ManyToManyField(to='seller.attribute'),
        ),
    ]
