# Generated by Django 5.2.11 on 2026-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_remove_attribute_sub_category_subcategory_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='seller.attribute'),
        ),
    ]
