# Generated by Django 5.2.11 on 2026-03-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_remove_coupon_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
